"""
extract_tournaments.py
Reads tourmap_v3_fixed.html and writes scraper/tournament_list.py,
which the scraper imports as its source-of-truth tournament list.

Run this whenever you update the tournament data in the HTML:
    python scraper/extract_tournaments.py

This is also run automatically by the GitHub Actions workflow before scraping.
"""

import re
import sys
from pathlib import Path

HTML_PATH = Path(__file__).parent.parent / "tourmap_v3_fixed.html"
OUT_PATH  = Path(__file__).parent / "tournament_list.py"


def extract():
    html = HTML_PATH.read_text(encoding="utf-8")

    # Each tournament is a JS object: {id:'...', tour:'...', ..., link:'...', ...}
    # We need: id, tour, start, end, link, name
    # Use a broad match and then pick fields
    chunks = re.findall(r"\{id:'[^']+',tour:'[^']+'.+?\}", html, re.S)

    def g(chunk, field):
        m = re.search(rf"{field}:'([^']*)'", chunk)
        return m.group(1) if m else ""

    tournaments = []
    seen = set()
    for chunk in chunks:
        tid = g(chunk, "id")
        if not tid or tid in seen:
            continue
        seen.add(tid)
        tournaments.append({
            "id":    tid,
            "name":  g(chunk, "name"),
            "tour":  g(chunk, "tour"),
            "start": g(chunk, "start"),
            "end":   g(chunk, "end"),
            "link":  g(chunk, "link"),
        })

    # Write Python module
    lines = [
        '"""',
        "Auto-generated by extract_tournaments.py — do not edit by hand.",
        '"""',
        "",
        "TOURNAMENTS = [",
    ]
    for t in tournaments:
        lines.append(
            f'    {{"id": {t["id"]!r}, "name": {t["name"]!r}, "tour": {t["tour"]!r}, '
            f'"start": {t["start"]!r}, "end": {t["end"]!r}, "link": {t["link"]!r}}},'
        )
    lines += ["]", ""]

    OUT_PATH.write_text("\n".join(lines), encoding="utf-8")
    print(f"✅ Wrote {len(tournaments)} tournaments to {OUT_PATH}")
    return len(tournaments)


if __name__ == "__main__":
    n = extract()
    sys.exit(0 if n > 0 else 1)
